// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

interface IMapSystem {
  function spawn(uint32 x, uint32 y) external;

  function getData() external view returns (uint32, uint32, uint32, bytes memory);

  function move(uint32 x, uint32 y, uint32 width, bytes calldata data) external;
}
